Add schema type for credits
illWatchers/ill-watch pull request #37
Opened 2018-11-28 20:00 UTC by flashlee

also I added `&append_to_response=credits` query to `Get Movie Details` request

2018-11-29 12:35 UTC, maybelinot requested changes

2018-11-29 12:35 UTC, maybelinot commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
we need to make that optional, otherwise we'll end up pulling everything

2018-12-08 14:40 UTC, flashlee commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
@maybelinot I added fetching of credits to this query because, afai, this query will be used for fetching whole info about movie. 
@alienalien13 wdyt?

2018-12-12 13:40 UTC, flashlee commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
> > this query will be used for fetching whole info about movie
> 
> IMHO that's a complete opposite of what graphql is meant to be used for, isn't it? We shouldn't have any query defined for particular use case, rather we'd want them to be dynamically generated based on requested fields.

You are right. But do we have use case where we need to fetch (by movie id) all info except credits?
Another problems is that we are building middleware graphql service, because we don't have our DB. We are using REST in the end. If we want to gain flexibility in gql request we will probably gain in numbers of REST request. For one use case are few REST requests. Only by this we will do a complete opposite of what graphql is meant to be used for.

2018-12-13 12:59 UTC, maybelinot commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
> You are right. But do we have use case where we need to fetch (by movie id) all info except credits?

I could use it for testing purposes, all the time getting unwanted data points is as min annoying.  
>  For one use case are few REST requests. Only by this we will do a complete opposite of what graphql is meant to be used for.

Not sure that I got what you meant here. I suggest to use `append_to_response` only when some of the fields from appended source was requested, why would that generate another another REST request?

2018-12-13 21:17 UTC, alienalien13 commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
I see what @maybelinot talks about, but I guess it doesn't break meaning gql at all because the client gets only data it requests anyway.

So I believe the way @flashlee has implemented this is not wrong.

2018-12-13 21:17 UTC, alienalien13 approved these changes

2018-12-14 11:20 UTC, maybelinot commented on src/theMovieDB.ts
> +    const data = await this.get(`movie/${movieId}?api_key=${this.apiKey}&append_to_response=credits`)
I didn't say it's wrong, what I'm saying is that it's not optimal solution.

At the end we'll be fetching credits, videos, images, etc. when we just need movie title. Client gets only what it requests, but server loads everything, even when he knows that he will not use it. Which is IMHO even worse than just using REST API from client :D 
Based on some smoke testing it takes ~60% more time for themoviedb to respond on a request with video,credits and images, rather than on a simple one.

> I see what @maybelinot talks about, but I guess it doesn't break meaning gql at all because the client gets only data it requests anyway.
The client will get only requested data even if we would pull a snapshot of whole themoviedb on each request, but I don't see any adequate reason to do that. Same here.

2018-12-14 14:29 UTC, alienalien13 requested changes

2019-01-05 19:13 UTC, merged